// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

import java_cup.runtime.Symbol;



@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\2\u0100\1\u0200\1\u0300\33\u0100\1\u0400\267\u0100\10\u0500"+
    "\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\0\1\6\1\7\4\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\11\17\2\0\1\20\1\21"+
    "\1\22\1\23\1\24\32\25\1\0\1\26\1\0\1\27"+
    "\1\25\1\0\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\2\25\1\41\1\25\1\42\1\43"+
    "\1\44\1\25\1\45\1\46\1\47\1\50\5\25\1\0"+
    "\1\51\1\0\1\52\6\0\1\3\33\0\1\53\35\0"+
    "\1\54\u01e3\0\1\55\251\0\1\56\6\0\1\57\323\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\2\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\1\1\21\14\20\1\22\1\1\1\23"+
    "\1\24\1\25\1\26\1\27\1\2\2\12\1\20\1\1"+
    "\14\20\1\27\1\30\1\31\1\0\1\32\1\33\1\34"+
    "\1\35\1\36\17\20\1\0\1\36\1\27\1\37\1\40"+
    "\1\41\1\42\1\43\17\20\1\36\1\44\6\20\1\45"+
    "\1\20\1\46\1\47\6\20\1\44\6\20\1\45\1\20"+
    "\1\46\1\47\6\20\1\50\1\51\1\20\1\52\3\20"+
    "\1\53\4\20\1\54\1\50\1\51\1\20\1\52\3\20"+
    "\1\53\4\20\1\54\1\20\1\55\1\56\1\57\5\20"+
    "\1\55\1\56\1\57\4\20\1\60\1\61\1\20\1\62"+
    "\1\63\1\60\1\61\1\20\1\62\1\63\4\20\2\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\140\0\140\0\140"+
    "\0\140\0\140\0\360\0\140\0\140\0\u0120\0\u0150\0\u0180"+
    "\0\u01b0\0\140\0\140\0\u01e0\0\u0210\0\140\0\u0240\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\u0420\0\u0450\0\140\0\u0480\0\140\0\140\0\140\0\140"+
    "\0\u04b0\0\u04e0\0\u04b0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0"+
    "\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750"+
    "\0\u0780\0\u07b0\0\u07e0\0\140\0\140\0\u0810\0\140\0\140"+
    "\0\140\0\140\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930"+
    "\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0"+
    "\0\u0ae0\0\u0b10\0\u0480\0\140\0\u0b40\0\140\0\140\0\140"+
    "\0\140\0\140\0\u0b70\0\u0ba0\0\u0bd0\0\u0c00\0\u0c30\0\u0c60"+
    "\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\u0de0"+
    "\0\u0e10\0\u04b0\0\u0810\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00"+
    "\0\u0f30\0\u01e0\0\u0f60\0\u01e0\0\u01e0\0\u0f90\0\u0fc0\0\u0ff0"+
    "\0\u1020\0\u1050\0\u1080\0\u0b40\0\u10b0\0\u10e0\0\u1110\0\u1140"+
    "\0\u1170\0\u11a0\0\u0540\0\u11d0\0\u0540\0\u0540\0\u1200\0\u1230"+
    "\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u01e0\0\u01e0\0\u1320\0\u01e0"+
    "\0\u1350\0\u1380\0\u13b0\0\u01e0\0\u13e0\0\u1410\0\u1440\0\u1470"+
    "\0\u01e0\0\u0540\0\u0540\0\u14a0\0\u0540\0\u14d0\0\u1500\0\u1530"+
    "\0\u0540\0\u1560\0\u1590\0\u15c0\0\u15f0\0\u0540\0\u1620\0\u01e0"+
    "\0\u01e0\0\u01e0\0\u1650\0\u1680\0\u16b0\0\u16e0\0\u1710\0\u0540"+
    "\0\u0540\0\u0540\0\u1740\0\u1770\0\u17a0\0\u17d0\0\u01e0\0\u01e0"+
    "\0\u1800\0\u01e0\0\u01e0\0\u0540\0\u0540\0\u1830\0\u0540\0\u0540"+
    "\0\u1860\0\u1890\0\u18c0\0\u18f0\0\u01e0\0\u0540";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\6\1\3\1\7\1\10"+
    "\1\11\1\12\1\13\1\3\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\24"+
    "\1\27\1\30\1\31\1\32\1\33\2\24\1\34\1\35"+
    "\1\24\1\36\1\37\1\40\1\41\1\42\1\24\1\3"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\4\2\51\1\6\10\51\1\53\1\54\5\51\1\55"+
    "\1\56\1\51\1\55\1\57\1\60\1\61\1\62\1\63"+
    "\2\55\1\64\1\65\1\55\1\66\1\67\1\70\1\71"+
    "\1\72\1\55\2\51\1\73\4\51\61\0\2\4\76\0"+
    "\1\74\60\0\1\75\51\0\1\76\1\0\2\16\61\0"+
    "\1\77\57\0\1\100\57\0\1\101\54\0\2\24\5\0"+
    "\1\24\2\0\21\24\15\0\1\102\42\0\1\103\24\0"+
    "\2\24\5\0\1\24\2\0\13\24\1\104\5\24\25\0"+
    "\2\24\5\0\1\24\2\0\7\24\1\105\11\24\25\0"+
    "\2\24\5\0\1\24\2\0\4\24\1\106\14\24\25\0"+
    "\2\24\5\0\1\24\2\0\11\24\1\107\7\24\25\0"+
    "\2\24\5\0\1\24\2\0\1\110\10\24\1\111\1\24"+
    "\1\112\5\24\25\0\2\24\5\0\1\24\2\0\12\24"+
    "\1\113\6\24\25\0\2\24\5\0\1\24\2\0\4\24"+
    "\1\114\6\24\1\115\5\24\25\0\2\24\5\0\1\24"+
    "\2\0\20\24\1\116\25\0\2\24\5\0\1\24\2\0"+
    "\15\24\1\117\3\24\25\0\2\24\5\0\1\24\2\0"+
    "\4\24\1\120\14\24\25\0\2\24\5\0\1\24\2\0"+
    "\17\24\1\121\1\24\25\0\2\24\5\0\1\24\2\0"+
    "\15\24\1\122\3\24\7\0\4\123\1\124\53\123\2\51"+
    "\1\0\2\51\1\0\20\51\1\0\32\51\1\52\1\4"+
    "\2\51\1\0\20\51\1\0\33\51\1\0\2\51\1\0"+
    "\6\51\1\125\1\51\2\54\6\51\1\0\33\51\1\0"+
    "\2\51\1\0\10\51\2\55\5\51\1\55\1\0\1\51"+
    "\21\55\7\51\5\0\1\126\1\102\17\0\1\127\13\0"+
    "\1\130\2\0\1\131\1\0\1\132\1\0\1\103\6\0"+
    "\2\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\13\55\1\133\5\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\7\55"+
    "\1\134\11\55\11\51\1\0\2\51\1\0\10\51\2\55"+
    "\5\51\1\55\1\0\1\51\4\55\1\135\14\55\11\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\11\55\1\136\7\55\11\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\1\137\10\55"+
    "\1\140\1\55\1\141\5\55\11\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\12\55\1\142"+
    "\6\55\11\51\1\0\2\51\1\0\10\51\2\55\5\51"+
    "\1\55\1\0\1\51\4\55\1\143\6\55\1\144\5\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\20\55\1\145\11\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\15\55\1\146"+
    "\3\55\11\51\1\0\2\51\1\0\10\51\2\55\5\51"+
    "\1\55\1\0\1\51\4\55\1\147\14\55\11\51\1\0"+
    "\2\51\1\0\10\51\2\55\5\51\1\55\1\0\1\51"+
    "\17\55\1\150\1\55\11\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\15\55\1\151\3\55"+
    "\7\51\2\73\1\123\1\73\1\152\1\123\20\73\1\123"+
    "\31\73\16\0\1\76\1\153\40\0\2\103\2\0\54\103"+
    "\16\0\2\24\5\0\1\24\2\0\13\24\1\154\5\24"+
    "\25\0\2\24\5\0\1\24\2\0\1\155\20\24\25\0"+
    "\2\24\5\0\1\24\2\0\2\24\1\156\16\24\25\0"+
    "\2\24\5\0\1\24\2\0\16\24\1\157\2\24\25\0"+
    "\2\24\5\0\1\24\2\0\11\24\1\160\7\24\25\0"+
    "\2\24\5\0\1\24\2\0\13\24\1\161\5\24\25\0"+
    "\2\24\5\0\1\24\2\0\15\24\1\162\3\24\25\0"+
    "\2\24\5\0\1\24\2\0\14\24\1\163\2\24\1\164"+
    "\1\24\25\0\2\24\5\0\1\24\2\0\17\24\1\165"+
    "\1\24\25\0\2\24\5\0\1\24\2\0\13\24\1\166"+
    "\5\24\25\0\2\24\5\0\1\24\2\0\17\24\1\167"+
    "\1\24\25\0\2\24\5\0\1\24\2\0\10\24\1\170"+
    "\10\24\25\0\2\24\5\0\1\24\2\0\17\24\1\171"+
    "\1\24\25\0\2\24\5\0\1\24\2\0\15\24\1\172"+
    "\3\24\25\0\2\24\5\0\1\24\2\0\20\24\1\173"+
    "\7\0\2\51\1\0\2\51\1\0\10\51\1\125\1\174"+
    "\6\51\1\0\33\51\1\0\2\51\1\0\10\51\2\55"+
    "\5\51\1\55\1\0\1\51\13\55\1\175\5\55\11\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\1\176\20\55\11\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\2\55\1\177\16\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\16\55\1\200\2\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\11\55"+
    "\1\201\7\55\11\51\1\0\2\51\1\0\10\51\2\55"+
    "\5\51\1\55\1\0\1\51\13\55\1\202\5\55\11\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\15\55\1\203\3\55\11\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\14\55\1\204"+
    "\2\55\1\205\1\55\11\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\17\55\1\206\1\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\13\55\1\207\5\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\17\55"+
    "\1\210\1\55\11\51\1\0\2\51\1\0\10\51\2\55"+
    "\5\51\1\55\1\0\1\51\10\55\1\211\10\55\11\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\17\55\1\212\1\55\11\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\15\55\1\213"+
    "\3\55\11\51\1\0\2\51\1\0\10\51\2\55\5\51"+
    "\1\55\1\0\1\51\20\55\1\214\7\51\16\0\2\24"+
    "\5\0\1\24\2\0\11\24\1\215\7\24\25\0\2\24"+
    "\5\0\1\24\2\0\15\24\1\216\3\24\25\0\2\24"+
    "\5\0\1\24\2\0\10\24\1\217\10\24\25\0\2\24"+
    "\5\0\1\24\2\0\4\24\1\220\14\24\25\0\2\24"+
    "\5\0\1\24\2\0\16\24\1\221\2\24\25\0\2\24"+
    "\5\0\1\24\2\0\1\222\20\24\25\0\2\24\5\0"+
    "\1\24\2\0\20\24\1\223\25\0\2\24\5\0\1\24"+
    "\2\0\14\24\1\224\4\24\25\0\2\24\5\0\1\24"+
    "\2\0\14\24\1\225\4\24\25\0\2\24\5\0\1\24"+
    "\2\0\12\24\1\226\6\24\25\0\2\24\5\0\1\24"+
    "\2\0\20\24\1\227\25\0\2\24\5\0\1\24\2\0"+
    "\10\24\1\230\10\24\25\0\2\24\5\0\1\24\2\0"+
    "\4\24\1\231\14\24\7\0\2\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\11\55\1\232"+
    "\7\55\11\51\1\0\2\51\1\0\10\51\2\55\5\51"+
    "\1\55\1\0\1\51\15\55\1\233\3\55\11\51\1\0"+
    "\2\51\1\0\10\51\2\55\5\51\1\55\1\0\1\51"+
    "\10\55\1\234\10\55\11\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\4\55\1\235\14\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\16\55\1\236\2\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\1\237"+
    "\20\55\11\51\1\0\2\51\1\0\10\51\2\55\5\51"+
    "\1\55\1\0\1\51\20\55\1\240\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\14\55"+
    "\1\241\4\55\11\51\1\0\2\51\1\0\10\51\2\55"+
    "\5\51\1\55\1\0\1\51\14\55\1\242\4\55\11\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\12\55\1\243\6\55\11\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\20\55\1\244"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\10\55\1\245\10\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\4\55"+
    "\1\246\14\55\7\51\16\0\2\24\5\0\1\24\2\0"+
    "\3\24\1\247\15\24\25\0\2\24\5\0\1\24\2\0"+
    "\4\24\1\250\14\24\25\0\2\24\5\0\1\24\2\0"+
    "\17\24\1\251\1\24\25\0\2\24\5\0\1\24\2\0"+
    "\17\24\1\252\1\24\25\0\2\24\5\0\1\24\2\0"+
    "\20\24\1\253\25\0\2\24\5\0\1\24\2\0\2\24"+
    "\1\254\16\24\25\0\2\24\5\0\1\24\2\0\15\24"+
    "\1\255\3\24\25\0\2\24\5\0\1\24\2\0\12\24"+
    "\1\256\6\24\7\0\2\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\3\55\1\257\15\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\4\55\1\260\14\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\17\55"+
    "\1\261\1\55\11\51\1\0\2\51\1\0\10\51\2\55"+
    "\5\51\1\55\1\0\1\51\17\55\1\262\1\55\11\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\20\55\1\263\11\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\2\55\1\264\16\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\15\55\1\265\3\55\11\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\12\55"+
    "\1\266\6\55\7\51\16\0\2\24\5\0\1\24\2\0"+
    "\4\24\1\267\14\24\25\0\2\24\5\0\1\24\2\0"+
    "\17\24\1\270\1\24\25\0\2\24\5\0\1\24\2\0"+
    "\10\24\1\271\10\24\25\0\2\24\5\0\1\24\2\0"+
    "\12\24\1\272\6\24\25\0\2\24\5\0\1\24\2\0"+
    "\6\24\1\273\12\24\7\0\2\51\1\0\2\51\1\0"+
    "\10\51\2\55\5\51\1\55\1\0\1\51\4\55\1\274"+
    "\14\55\11\51\1\0\2\51\1\0\10\51\2\55\5\51"+
    "\1\55\1\0\1\51\17\55\1\275\1\55\11\51\1\0"+
    "\2\51\1\0\10\51\2\55\5\51\1\55\1\0\1\51"+
    "\10\55\1\276\10\55\11\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\12\55\1\277\6\55"+
    "\11\51\1\0\2\51\1\0\10\51\2\55\5\51\1\55"+
    "\1\0\1\51\6\55\1\300\12\55\7\51\16\0\2\24"+
    "\5\0\1\24\2\0\14\24\1\301\4\24\7\0\2\51"+
    "\1\0\2\51\1\0\10\51\2\55\5\51\1\55\1\0"+
    "\1\51\14\55\1\302\4\55\7\51\16\0\2\24\5\0"+
    "\1\24\2\0\1\303\20\24\7\0\2\51\1\0\2\51"+
    "\1\0\10\51\2\55\5\51\1\55\1\0\1\51\1\304"+
    "\20\55\7\51\16\0\2\24\5\0\1\24\2\0\11\24"+
    "\1\305\7\24\7\0\2\51\1\0\2\51\1\0\10\51"+
    "\2\55\5\51\1\55\1\0\1\51\11\55\1\306\7\55"+
    "\7\51";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6432];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\5\11\1\1\2\11\4\1\2\11"+
    "\2\1\1\11\14\1\1\11\1\1\4\11\23\1\2\11"+
    "\1\0\4\11\20\1\1\0\1\11\1\1\5\11\154\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private StringBuilder string_lit;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Símbolo no reconocido: " + yytext() + " en línea " + yyline);
            }
          // fall through
          case 53: break;
          case 2:
            { /* ignorar espacios */
            }
          // fall through
          case 54: break;
          case 3:
            { string_lit = new StringBuilder(); yybegin(STRING);
            }
          // fall through
          case 55: break;
          case 4:
            { return new Symbol(sym.MOD, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 5:
            { return new Symbol(sym.MULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 6:
            { return new Symbol(sym.PLUS, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 7:
            { return new Symbol(sym.COMMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 8:
            { return new Symbol(sym.MINUS, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 9:
            { return new Symbol(sym.DIV, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 10:
            { return new Symbol(sym.INT_LIT, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 11:
            { return new Symbol(sym.LT, yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 12:
            { return new Symbol(sym.ASSIGN, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 13:
            { return new Symbol(sym.GT, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 14:
            { return new Symbol(sym.RBLOCK, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 15:
            { return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 16:
            { return new Symbol(sym.ID, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 17:
            { return new Symbol(sym.POW, yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 18:
            { return new Symbol(sym.OR, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 19:
            { return new Symbol(sym.LBLOCK, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 20:
            { return new Symbol(sym.SIGMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 21:
            { return new Symbol(sym.RPAREN, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 22:
            { return new Symbol(sym.LPAREN, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 23:
            { string_lit.append(yytext());
            }
          // fall through
          case 75: break;
          case 24:
            { return new Symbol(sym.NEQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 25:
            { return new Symbol(sym.ARROW, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 26:
            { return new Symbol(sym.LE, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 27:
            { return new Symbol(sym.EQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 28:
            { return new Symbol(sym.GE, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 29:
            { return new Symbol(sym.DOLLAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 30:
            { /* ignorar comentarios */
            }
          // fall through
          case 82: break;
          case 31:
            { string_lit.append('\"');
            }
          // fall through
          case 83: break;
          case 32:
            { string_lit.append('\\');
            }
          // fall through
          case 84: break;
          case 33:
            { string_lit.append('\n');
            }
          // fall through
          case 85: break;
          case 34:
            { string_lit.append('\r');
            }
          // fall through
          case 86: break;
          case 35:
            { string_lit.append('\t');
            }
          // fall through
          case 87: break;
          case 36:
            { return new Symbol(sym.FLOAT_LIT, yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 37:
            { return new Symbol(sym.FOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 38:
            { return new Symbol(sym.INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 39:
            { return new Symbol(sym.LET, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 40:
            { return new Symbol(sym.BOOL, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 41:
            { return new Symbol(sym.CHAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 42:
            { return new Symbol(sym.ELSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 43:
            { return new Symbol(sym.LOOP, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 44:
            { return new Symbol(sym.TRUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 45:
            { return new Symbol(sym.FALSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 46:
            { return new Symbol(sym.FLOAT, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 47:
            { return new Symbol(sym.INPUT, yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 48:
            { return new Symbol(sym.DECIDE, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 49:
            { return new Symbol(sym.OUTPUT, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 50:
            { return new Symbol(sym.RETURN, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          case 51:
            { return new Symbol(sym.STRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 103: break;
          case 52:
            { return new Symbol(sym.PRINCIPAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
