
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 29;
  public static final int CHAR_LIT = 30;
  public static final int POW = 47;
  public static final int WHEN = 21;
  public static final int LBRACKET = 37;
  public static final int MULT = 43;
  public static final int CHAR = 6;
  public static final int GE = 54;
  public static final int OUTPUT = 11;
  public static final int INPUT = 10;
  public static final int LPAREN = 33;
  public static final int INT = 3;
  public static final int SIGMA = 59;
  public static final int MINUS = 42;
  public static final int FOR = 22;
  public static final int RPAREN = 34;
  public static final int PRINCIPAL = 9;
  public static final int AND = 57;
  public static final int LT = 55;
  public static final int DECIDE = 15;
  public static final int OR = 58;
  public static final int COMMA = 39;
  public static final int BOOL = 5;
  public static final int INC = 48;
  public static final int DIV = 44;
  public static final int PLUS = 41;
  public static final int LOOP = 19;
  public static final int EXIT = 20;
  public static final int ASSIGN = 50;
  public static final int ID = 27;
  public static final int LE = 56;
  public static final int OF = 16;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 38;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int LBLOCK = 35;
  public static final int MOD = 46;
  public static final int NEQ = 52;
  public static final int DIVINT = 45;
  public static final int VOID = 8;
  public static final int EQ = 51;
  public static final int RBLOCK = 36;
  public static final int ARROW = 40;
  public static final int ELSE = 17;
  public static final int TO = 24;
  public static final int DOLLAR = 32;
  public static final int LET = 2;
  public static final int FLOAT = 4;
  public static final int END = 18;
  public static final int STRING = 7;
  public static final int DOWNTO = 25;
  public static final int DEC = 49;
  public static final int FALSE = 14;
  public static final int STRING_LIT = 31;
  public static final int GT = 53;
  public static final int INT_LIT = 28;
  public static final int DO = 26;
  public static final int STEP = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LET",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "PRINCIPAL",
  "INPUT",
  "OUTPUT",
  "RETURN",
  "TRUE",
  "FALSE",
  "DECIDE",
  "OF",
  "ELSE",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "STEP",
  "TO",
  "DOWNTO",
  "DO",
  "ID",
  "INT_LIT",
  "FLOAT_LIT",
  "CHAR_LIT",
  "STRING_LIT",
  "DOLLAR",
  "LPAREN",
  "RPAREN",
  "LBLOCK",
  "RBLOCK",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "ARROW",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "DIVINT",
  "MOD",
  "POW",
  "INC",
  "DEC",
  "ASSIGN",
  "EQ",
  "NEQ",
  "GT",
  "GE",
  "LT",
  "LE",
  "AND",
  "OR",
  "SIGMA"
  };
}

